// react/src/App.tsx
import { Routes } from 'react-router'
import { routes } from './router'

function App() {
  return (
    <>
      <h1>You did it!</h1>
      <p>
        Visit{' '}
        <a href="https://react.dev/" target="_blank" rel="noopener">
          react.dev
        </a>{' '}
        to read the documentation
      </p>
      <Routes>{routes}</Routes>
    </>
  )
}

export default App

// angular/src/app/app.component.ts
import { Component } from '@angular/core'
import { RouterOutlet } from '@angular/router'

@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  template: `
    <h1>You did it!</h1>
    <p>
      Visit
      <a href="https://angular.dev/" target="_blank" rel="noopener">angular.dev</a>
      to read the documentation
    </p>
    <router-outlet />
  `,
})
export class AppComponent {}
